import Vote from "@/components/Vote";
import { auth } from "@/config/firebase";
import { useName } from "@/hooks/useName";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { useAuthState } from "react-firebase-hooks/auth";

export default function Home() {
  const [user, loading, error] = useAuthState(auth);
  const router = useRouter();
  const name = useName(user);
  useEffect(() => {
    if (!user && !loading) {
      router.push("/login");
    }
  }, [router, user, loading]);

  return (
    <>
      <Head>
        <title>jVote</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex justify-center items-center h-screen">
        {loading && <h1 className="text-white text-4xl">Loading...</h1>}
        {user && (
          <div className="flex flex-col space-y-20">
            <h1 className="text-8xl text-fuchsia-300 text-center">
              Hei {name} 👊
            </h1>
            <Vote />
          </div>
        )}
      </div>
    </>
  );
}
